

const MATCHES_LIST_REQUEST = 'MATCHES_LIST_REQUEST';
const MATCHES_LIST_SUCCESS = 'MATCHES_LIST_SUCCESS';
const MATCHES_LIST_FAILURE = 'MATCHES_LIST_FAILURE';
const MATCH_ADD_REQUEST = 'MATCH_ADD_REQUEST';
const MATCH_ADD_SUCCESS = 'MATCH_ADD_SUCCESS'
const MATCH_ADD_FAILURE = 'MATCH_ADD_FAILURE'
const MATCH_DELETE_REQUEST = 'MATCH_DELETE_REQUEST'
const MATCH_DELETE_SUCCESS = 'MATCH_DELETE_SUCCESS'
const MATCH_DELETE_FAILURE = 'MATCH_DELETE_FAILURE'
const MATCH_EDIT_REQUEST = 'MATCH_EDIT_REQUEST'
const MATCH_EDIT_SUCCESS = 'MATCH_EDIT_SUCCESS'
const MATCH_EDIT_FAILURE = 'MATCH_EDIT_FAILURE'
const types = {

    MATCHES_LIST_REQUEST,
    MATCHES_LIST_SUCCESS,
    MATCHES_LIST_FAILURE,
    MATCH_ADD_SUCCESS,
    MATCH_ADD_REQUEST,
    MATCH_ADD_FAILURE,
    MATCH_DELETE_REQUEST,
    MATCH_DELETE_SUCCESS,
    MATCH_DELETE_FAILURE,
    MATCH_EDIT_REQUEST,
    MATCH_EDIT_SUCCESS,
    MATCH_EDIT_FAILURE,

};

export default types;