

const OBJECTS_LIST_REQUEST = 'OBJECTS_LIST_REQUEST';
const OBJECTS_LIST_SUCCESS = 'OBJECTS_LIST_SUCCESS';
const OBJECTS_LIST_FAILURE = 'OBJECTS_LIST_FAILURE';
const OBJECT_ADD_REQUEST = 'OBJECT_ADD_REQUEST';
const OBJECT_ADD_SUCCESS = 'OBJECT_ADD_SUCCESS'
const OBJECT_ADD_FAILURE = 'OBJECT_ADD_FAILURE'
const OBJECT_DELETE_REQUEST = 'OBJECT_DELETE_REQUEST'
const OBJECT_DELETE_SUCCESS = 'OBJECT_DELETE_SUCCESS'
const OBJECT_DELETE_FAILURE = 'OBJECT_DELETE_FAILURE'
const OBJECT_EDIT_REQUEST ='OBJECT_EDIT_REQUEST'
const OBJECT_EDIT_SUCCESS = 'OBJECT_EDIT_SUCCESS'
const OBJECT_EDIT_FAILURE = 'OBJECT_EDIT_FAILURE'

const types = {

    OBJECTS_LIST_REQUEST,
    OBJECTS_LIST_SUCCESS,
    OBJECTS_LIST_FAILURE,
    OBJECT_ADD_SUCCESS,
    OBJECT_ADD_REQUEST,
    OBJECT_ADD_FAILURE,
    OBJECT_DELETE_REQUEST,
    OBJECT_DELETE_SUCCESS,
    OBJECT_DELETE_FAILURE,
    OBJECT_EDIT_REQUEST,
    OBJECT_EDIT_SUCCESS,
    OBJECT_EDIT_FAILURE
};

export default types;