

const PLAYERS_LIST_REQUEST = 'PLAYERS_LIST_REQUEST';
const PLAYERS_LIST_SUCCESS = 'PLAYERS_LIST_SUCCESS';
const PLAYERS_LIST_FAILURE = 'PLAYERS_LIST_FAILURE';
const PLAYER_ADD_REQUEST = 'PLAYER_ADD_REQUEST';
const PLAYER_ADD_SUCCESS = 'PLAYER_ADD_SUCCESS'
const PLAYER_ADD_FAILURE = 'PLAYER_ADD_FAILURE'
const PLAYER_DELETE_REQUEST = 'PLAYER_DELETE_REQUEST'
const PLAYER_DELETE_SUCCESS = 'PLAYER_DELETE_SUCCESS'
const PLAYER_DELETE_FAILURE = 'PLAYER_DELETE_FAILURE'
const PLAYER_EDIT_REQUEST = 'PLAYER_EDIT_REQUEST'
const PLAYER_EDIT_SUCCESS = 'PLAYER_EDIT_SUCCESS'
const PLAYER_EDIT_FAILURE = 'PLAYER_EDIT_FAILURE'


const types = {

    PLAYERS_LIST_REQUEST,
    PLAYERS_LIST_SUCCESS,
    PLAYERS_LIST_FAILURE,
    PLAYER_ADD_SUCCESS,
    PLAYER_ADD_REQUEST,
    PLAYER_ADD_FAILURE,
    PLAYER_DELETE_REQUEST,
    PLAYER_DELETE_SUCCESS,
    PLAYER_DELETE_FAILURE,
    PLAYER_EDIT_REQUEST,
    PLAYER_EDIT_SUCCESS,
    PLAYER_EDIT_FAILURE
};

export default types;